"""marginalia setup wizard — guided first-run configuration."""
from __future__ import annotations

import os
import platform
import shutil
import socket
import subprocess
import sys
import textwrap
from pathlib import Path

# ── ANSI colours (disabled on Windows or when not a tty) ─────────────────────

_COLOUR = sys.stdout.isatty() and platform.system() != "Windows"

def _c(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _COLOUR else text

def green(t):  return _c("32", t)
def yellow(t): return _c("33", t)
def cyan(t):   return _c("36", t)
def bold(t):   return _c("1",  t)
def dim(t):    return _c("2",  t)

# ── Helpers ───────────────────────────────────────────────────────────────────

CONFIG_FILE = Path.home() / ".marginalia.env"
BRIDGE_DIR  = Path(__file__).parent


def _ask(prompt: str, default: str = "") -> str:
    hint = f" [{default}]" if default else ""
    try:
        val = input(f"  {prompt}{hint}: ").strip()
    except (EOFError, KeyboardInterrupt):
        print("\nAborted.")
        sys.exit(0)
    return val or default


def _pick(prompt: str, options: list[tuple[str, str]], default: int = 1) -> int:
    """Numbered menu. Returns 1-based index of the choice."""
    print(f"\n  {prompt}")
    for i, (label, desc) in enumerate(options, 1):
        marker = green("►") if i == default else " "
        print(f"  {marker} {i}. {bold(label)}{f'  — {dim(desc)}' if desc else ''}")
    while True:
        raw = _ask(f"Choice", str(default))
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return int(raw)
        print(yellow(f"  Please enter a number between 1 and {len(options)}."))


def _ok(msg: str):   print(f"  {green('✓')} {msg}")
def _warn(msg: str): print(f"  {yellow('⚠')} {msg}")
def _err(msg: str):  print(f"  \033[31m✗\033[0m {msg}" if _COLOUR else f"  ✗ {msg}")
def _hdr(msg: str):  print(f"\n{bold(cyan('── ' + msg + ' ──'))}")


def _local_ip() -> str:
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return "?.?.?.?"


def _mdns_name() -> str:
    try:
        h = socket.gethostname()
        return h if h.endswith(".local") else h + ".local"
    except Exception:
        return ""


def _find_vaults(max_results: int = 8) -> list[Path]:
    """Walk common locations for .obsidian directories."""
    candidates = [
        Path.home() / "Documents",
        Path.home() / "Dropbox",
        Path.home() / "iCloud Drive",
        Path.home() / "OneDrive",
        Path.home(),
    ]
    vaults: list[Path] = []
    seen: set[Path] = set()
    for base in candidates:
        if not base.is_dir():
            continue
        try:
            for item in base.iterdir():
                if not item.is_dir():
                    continue
                obsidian = item / ".obsidian"
                if obsidian.is_dir() and item not in seen:
                    vaults.append(item)
                    seen.add(item)
                # One level deeper
                try:
                    for sub in item.iterdir():
                        if sub.is_dir() and (sub / ".obsidian").is_dir() and sub not in seen:
                            vaults.append(sub)
                            seen.add(sub)
                except PermissionError:
                    pass
        except PermissionError:
            pass
        if len(vaults) >= max_results:
            break
    return vaults[:max_results]


def _load_existing() -> dict[str, str]:
    """Load existing config from ~/.marginalia.env."""
    cfg: dict[str, str] = {}
    if CONFIG_FILE.exists():
        for line in CONFIG_FILE.read_text().splitlines():
            line = line.strip()
            if line.startswith("export ") and "=" in line:
                k, _, v = line[len("export "):].partition("=")
                cfg[k.strip()] = v.strip().strip('"').strip("'")
    return cfg


def _write_config(cfg: dict[str, str]) -> None:
    lines = [
        "# marginalia configuration — generated by 'marginalia setup'",
        "# source this file: set -a && source ~/.marginalia.env && set +a",
        "",
    ]
    for k, v in cfg.items():
        # Quote values that contain spaces
        val = f'"{v}"' if " " in v else v
        lines.append(f"export {k}={val}")
    CONFIG_FILE.write_text("\n".join(lines) + "\n")


# ── Provider setup ────────────────────────────────────────────────────────────

def _setup_openai(cfg: dict[str, str]) -> bool:
    existing = cfg.get("MARGINALIA_OPENAI_API_KEY", "")
    hint = f"(current: {existing[:10]}…)" if existing else "(starts with sk-...)"
    key = _ask(f"OpenAI API key {dim(hint)}", existing)
    if not key:
        _warn("Skipped — you can set MARGINALIA_OPENAI_API_KEY later.")
        return False
    print(f"  {dim('Testing key…')}", end="", flush=True)
    try:
        import openai
        client = openai.OpenAI(api_key=key)
        client.models.list()
        print(f"\r  {green('✓')} OpenAI key valid")
        cfg["MARGINALIA_OPENAI_API_KEY"] = key
        cfg.setdefault("MARGINALIA_MODEL_ID", "openai:gpt-4o")
        return True
    except ImportError:
        print()
        _err("openai package not installed. Run: pip install 'marginalia[openai]'")
        cfg["MARGINALIA_OPENAI_API_KEY"] = key  # save anyway
        return True
    except Exception as e:
        print()
        _err(f"Key rejected: {e}")
        return False


def _setup_anthropic(cfg: dict[str, str]) -> bool:
    existing = cfg.get("MARGINALIA_ANTHROPIC_API_KEY", "")
    hint = f"(current: {existing[:12]}…)" if existing else "(starts with sk-ant-...)"
    key = _ask(f"Anthropic API key {dim(hint)}", existing)
    if not key:
        _warn("Skipped.")
        return False
    print(f"  {dim('Testing key…')}", end="", flush=True)
    try:
        import anthropic
        client = anthropic.Anthropic(api_key=key)
        client.models.list()
        print(f"\r  {green('✓')} Anthropic key valid")
        cfg["MARGINALIA_ANTHROPIC_API_KEY"] = key
        cfg.setdefault("MARGINALIA_MODEL_ID", "anthropic:claude-opus-4-5")
        return True
    except ImportError:
        print()
        _err("anthropic package not installed. Run: pip install 'marginalia[anthropic]'")
        cfg["MARGINALIA_ANTHROPIC_API_KEY"] = key
        return True
    except Exception as e:
        print()
        _err(f"Key rejected: {e}")
        return False


def _setup_bedrock(cfg: dict[str, str]) -> bool:
    existing = cfg.get("MARGINALIA_AWS_PROFILE", "")
    profile = _ask("AWS profile name", existing or "default")
    print(f"  {dim('Testing credentials…')}", end="", flush=True)
    try:
        import boto3
        session = boto3.Session(profile_name=profile, region_name="us-west-2")
        sts = session.client("sts")
        sts.get_caller_identity()
        print(f"\r  {green('✓')} AWS credentials valid")
        cfg["MARGINALIA_AWS_PROFILE"] = profile
        cfg.setdefault("MARGINALIA_MODEL_ID", "us.anthropic.claude-sonnet-4-6")
        return True
    except ImportError:
        print()
        _err("boto3 not installed. Run: pip install 'marginalia[bedrock]'")
        cfg["MARGINALIA_AWS_PROFILE"] = profile
        return True
    except Exception as e:
        print()
        _err(f"Credentials failed: {e}")
        return False


# ── Vault setup ───────────────────────────────────────────────────────────────

def _setup_vault(cfg: dict[str, str]) -> None:
    vaults = _find_vaults()
    existing = cfg.get("MARGINALIA_VAULT", "")

    if vaults:
        opts = [(str(v), dim(str(v).replace(str(Path.home()), "~"))) for v in vaults]
        opts.append(("Enter path manually", ""))
        choice = _pick("Which Obsidian vault should book notes go to?", opts)
        if choice <= len(vaults):
            vault = str(vaults[choice - 1])
        else:
            vault = _ask("Vault path", existing or str(Path.home() / "Documents"))
            vault = os.path.expanduser(vault)
    else:
        _warn("No Obsidian vaults detected. Enter the path to your vault root.")
        vault = _ask("Vault path", existing or str(Path.home() / "Documents"))
        vault = os.path.expanduser(vault)

    cfg["MARGINALIA_VAULT"] = vault
    _ok(f"Vault: {vault}")


# ── Service install ───────────────────────────────────────────────────────────

def _install_macos(cfg: dict[str, str]) -> None:
    install_sh = BRIDGE_DIR / "install.sh"
    if not install_sh.exists():
        _warn("install.sh not found — skipping LaunchAgent setup.")
        return
    env = {**os.environ, **{k: v for k, v in cfg.items()}}
    result = subprocess.run(
        ["bash", str(install_sh)],
        env=env,
        cwd=str(BRIDGE_DIR),
    )
    if result.returncode != 0:
        _warn("LaunchAgent install reported an error — check the output above.")


def _install_linux(cfg: dict[str, str]) -> None:
    service_src = BRIDGE_DIR / "marginalia.service"
    service_dst = Path.home() / ".config" / "systemd" / "user" / "marginalia.service"
    if not service_src.exists():
        _warn("marginalia.service not found.")
        return
    service_dst.parent.mkdir(parents=True, exist_ok=True)
    # Build the service file with real values
    content = service_src.read_text()
    venv_python = sys.executable
    bridge_server = str(BRIDGE_DIR / "server.py")
    content = content.replace(
        "ExecStart=/usr/bin/python3 %h/marginalia/bridge/server.py",
        f"ExecStart={venv_python} {bridge_server}",
    ).replace(
        "WorkingDirectory=%h/marginalia/bridge",
        f"WorkingDirectory={BRIDGE_DIR}",
    )
    # Inject env vars
    env_lines = "\n".join(f"Environment={k}={v}" for k, v in cfg.items()
                           if k.startswith("MARGINALIA_"))
    content = content.replace(
        "Environment=MARGINALIA_MODEL_ID=openai:gpt-4o\n",
        env_lines + "\n",
    )
    service_dst.write_text(content)
    subprocess.run(["systemctl", "--user", "daemon-reload"], check=False)
    subprocess.run(["systemctl", "--user", "enable", "--now", "marginalia"], check=False)
    _ok(f"systemd service installed → {service_dst}")


def _setup_service(cfg: dict[str, str]) -> None:
    system = platform.system()
    if system == "Darwin":
        choice = _pick("Install as a background service?", [
            ("Yes — LaunchAgent (starts at login, restarts automatically)", ""),
            ("No — I'll run 'marginalia serve' manually", ""),
        ])
        if choice == 1:
            _install_macos(cfg)
    elif system == "Linux":
        choice = _pick("Install as a systemd user service?", [
            ("Yes — systemd (starts at login, restarts automatically)", ""),
            ("No — I'll run 'marginalia serve' manually", ""),
        ])
        if choice == 1:
            _install_linux(cfg)
    else:
        print(f"\n  {dim('Windows: run')} {bold('marginalia serve')} {dim('in a terminal.')}")
        print(f"  {dim('For auto-start, add it to Task Scheduler — see docs/setup.md.')}")


# ── KOReader instructions ──────────────────────────────────────────────────────

def _print_koreader_instructions() -> None:
    ip      = _local_ip()
    mdns    = _mdns_name()
    plugin  = BRIDGE_DIR.parent / "marginalia.koplugin"

    _hdr("KOReader plugin")
    print(f"""
  1. Copy the plugin to your device:
     {bold('ADB (Android/Boox):')}
       adb push {plugin} /sdcard/koreader/plugins/marginalia.koplugin

     {bold('File manager / MTP:')}  copy the {cyan('marginalia.koplugin/')} folder to
       your device's {cyan('koreader/plugins/')} directory.

  2. Restart KOReader.

  3. Go to {bold('top menu → Tools (wrench) → marginalia')} and set:
       {bold('Host')}: {green(ip)}  {dim(f'(or {mdns} if on the same Wi-Fi)')}
       {bold('Port')}: 7731

  4. Tap {bold('Test connection')} — you should see ✓ Connected.
    """)


# ── Main wizard ───────────────────────────────────────────────────────────────

def run() -> None:
    print(f"\n{bold(cyan('marginalia setup'))}")
    print(dim("  AI reading companion for KOReader\n"))

    existing = _load_existing()
    if existing:
        print(f"  Existing config found at {CONFIG_FILE}")
        choice = _pick("What would you like to do?", [
            ("Reconfigure", "change provider, vault, or service settings"),
            ("Keep existing config and just show KOReader instructions", ""),
            ("Exit", ""),
        ])
        if choice == 2:
            _print_koreader_instructions()
            return
        if choice == 3:
            return

    cfg = dict(existing)

    # ── Step 1: Provider ───────────────────────────────────────────────────
    _hdr("Step 1 — AI provider")

    provider_opts = [
        ("OpenAI",    "gpt-4o recommended — best quality, simplest setup"),
        ("Anthropic", "Claude — alternative to OpenAI"),
        ("Bedrock",   "AWS credentials required"),
        ("Skip",      "configure manually later"),
    ]
    provider = _pick("Which AI provider?", provider_opts)

    ok = False
    if provider == 1:
        ok = _setup_openai(cfg)
    elif provider == 2:
        ok = _setup_anthropic(cfg)
    elif provider == 3:
        ok = _setup_bedrock(cfg)
    else:
        _warn("Skipped — set MARGINALIA_OPENAI_API_KEY (or equivalent) before running.")

    if not ok and provider != 4:
        retry = _ask("Provider setup failed. Continue anyway? (y/n)", "n")
        if retry.lower() != "y":
            return

    # ── Step 2: Vault ─────────────────────────────────────────────────────
    _hdr("Step 2 — Obsidian vault")
    _setup_vault(cfg)

    # ── Step 3: Save config ───────────────────────────────────────────────
    _hdr("Step 3 — Save config")
    _write_config(cfg)
    _ok(f"Config written to {CONFIG_FILE}")
    print(f"  {dim('To load in a terminal session:')}")
    print(f"  {cyan('set -a && source ~/.marginalia.env && set +a')}\n")

    # ── Step 4: Service ───────────────────────────────────────────────────
    _hdr("Step 4 — Background service")
    _setup_service(cfg)

    # ── Step 5: KOReader ─────────────────────────────────────────────────
    _print_koreader_instructions()

    print(f"  {bold(green('Setup complete!'))} Run {bold('marginalia serve')} to start the bridge.\n")
